### ISSUE TITLE
Structure of release 3.1

### ISSUE THREAD

**Issue by spvickers** [WebPA/WebPA#74]
Release 3.1 has a different structure from previous releases; all the source files are included in a directory named _src_.  This means that when installing using composer the code is accessed at _.../webpa/src_ rather than just _.../webpa_ which is not very convenient.

**Comment by Sephster** [comment]
Hi Stephen. Sorry if this is causing any issues. The reason I've made this change is that it is in preparation of getting a front controller in the system. Eventually we should have an index file that serves all http requests. We can then put the src folder outside of the web dir entirely.

**Comment by spvickers** [comment]
In that case, perhaps you should remove the WebPA package from Packagist because it does not implement a helpful installation of WebPA.

**Comment by Sephster** [comment]
I don't think this creates significant issues for installation. You can change your webroot to point to the src directory instead of the root of the package, or manually move the src folder to wherever you housed WebPA previously.

If you install Laravel or Symfony, you won't be able to run the project from the root directory. They both come with _public_ directories which you have to point your webroot to. I aim to eventually have something similar in WebPA but still need to make changes to support a front controller so for now, the webroot should be pointed to src.

**Comment by spvickers** [comment]
Very true, though this does require more access to the server than some may have.  Furthermore, moving the src directory is not enough; you also have to move the vendor directory to the same parent directory (or edit the reference to the autoload.php file in inc_global.php).  Not impossible to do, but might benefit from adding to the composer installation instructions that they work best when the package is not installed within the web root.

**Comment by spvickers** [comment]
Further to my previous comment, if you change the relative position of the vendor directory to the src directory, then this must also be reflected in the composer autoload_psr4.php and autoload_static.php files (as well as changing the reference to the autoload.php file in inc_global.php).

Note also that, when installing manually from the release file, it is also necessary to create the vendor directory and an autoload.php file as these are not included in the repo.

**Comment by Sephster** [comment]
Thanks for this feedback Stephen. Do you think it would be worth adding an upgrade guide to note the structure change? I will get this added to help avoid confusion.

Because this is a project, there isn't a native way to upgrade via composer. It is expected that you would use create-project and then copy the files where ever or simply clone the repo and avoid composer entirely. 

If you have necessary permissions, composer should create the vendor folder and autoload.php file for you if they don't exist

**Comment by spvickers** [comment]
It may just be that the changes are not compatible with the way I normally work, and I suspect your experience is greater than mine in this area.  I normally take a very simple approach and install directly into the web root.  With the 3.1 release if I do this I get two directories (src and vendor).  If I install manually I just get src but need to then create my own vendor directory and autoload.php file.  So, for me, neither approach is as easy as it might be.

In my own repos, I include a vendor directory with a working autoload.php file (which is overwritten when using composer); this would make the manual install easier.

My only other query is whether it is necessary to have the vendor and src directories at the same level - could the vendor directory not also be inside src?  Would this happen if the composer.json file was moved inside src? (I've not tried doing this, but I believe that composer will search subdirectories for composer.json files.)  That would then make it easier to move src to wherever it is needed and name it as desired.

Finally, a note in the documentation on using the --no-dev option when installing via composer might be useful for those that do not need the phpstan dependency.

**Comment by Sephster** [comment]
Thanks for the feedback Stephen. I think on reflection this might require further edits in future to make upgrades and installs easier. My rough thoughts are as follows:


- This repo will have a `public` folder that will contain an index.php file
- At root, we will have a config file and the composer info etc
- The core of WebPA can then be moved to a separate package

By doing this, it means that in general, it would be unlikely you would change the structure of this repo. You'd just composer update and away to go.

It still means you would have to manually install or point the webroot to the public folder instead of root but I think it is important to keep most files outside of the webroot from a security perspective so I'd like to keep this in place. This is the main reason why I've currently got the vendor folders outside of src. There is no reason for them to be in the webroot so the less that is exposed the better.

Thanks for the changes suggested with `--no-dev`. I've updated the readme to include this and also added the `--prefer-dist` option.

I will also look to add an upgrade guide as it is clear the structure change could cause issues. Thanks very much for all of your help with this Stephen. It is appreciated.
